# Private repo are located on Gitlab CI
# This script exist here for archive and starter
image: "node:12-alpine"
variables:
  REMOTE_DESTINATION_DIR: ./dist
  CI_SYNC_TYPE: RSYNC
  STAGE_URL: https://staticdevstack.ecrannoir.be

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/

stages:
  - build
  - test
  - deploy

staging_build:
  stage: build
  only: 
    - staging
    - ci-feature
  before_script:
    - source .env
    - npm install
  script:
    - echo "Build step"
    - npm run build
  artifacts:
    paths:
      - ./dist/
  environment:
    name: stage
    url: $STAGE_URL

staging_rsync_deploy:
  stage: deploy
  only:
    refs:
      - staging
      - ci-feature
    variables:
      - $CI_SYNC_TYPE == "RSYNC"
  before_script:
    - source .env
    - 'which ssh-agent || ( apk --no-cache add rsync openssh-client )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Deploy step by rsync"
    - echo "$STAGING_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -p 44925 $STAGING_SSH_USER@$STAGING_SSH_HOST
    - rsync -azPqv -e 'ssh -p 44925' dist $STAGING_SSH_USER@$STAGING_SSH_HOST:$REMOTE_DESTINATION_DIR
  environment:
    name: stage
    url: $STAGE_URL
